#------------------------------------------------------------
#
#  用途: 开发环境的基础结构
#  构成: nginx:1.15.7
#
# @version    1.0
# @author     Luffy Zhao
#

#------------------------------------------------------------
# FROM
FROM phpswoole/swoole:4.5.9-php7.3


# Timezone
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone


# Timezone
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl \
    libicu-dev \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    libxml2-dev \
    libbz2-dev \
    libjpeg62-turbo-dev \
    curl \
    git \
  && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure bcmath --enable-bcmath
RUN docker-php-ext-configure pcntl --enable-pcntl
RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql 
RUN docker-php-ext-configure soap --enable-soap 

COPY libzip-1.2.0.tar.gz / 

RUN cd / && \
    tar -zxvf libzip-1.2.0.tar.gz && \
    cd libzip-1.2.0  && \
    ./configure && \
    make && make install

RUN docker-php-ext-install \
        bcmath \
        intl \
        mysqli \
        pcntl \
        pdo_mysql \
        pdo_pgsql \
        soap \
        zip

RUN docker-php-ext-configure gd \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2

RUN docker-php-ext-install gd 
RUN pecl install redis 
RUN docker-php-ext-enable redis

COPY composer /usr/local/bin/


EXPOSE 9501
EXPOSE 9502
EXPOSE 9503