version: '3'

services:
  php7.1:
    build: ./dockerfiles/php7.1
    networks:
      dev:
        aliases:
          - php
    volumes:
      - ./dockerfiles/php7.1/php-fpm.d:/usr/local/etc/php/php-fpm.d
      - ./dockerfiles/php7.1/conf.d:/usr/local/etc/php/conf.d
      - ./www:/var/www/html
    ports:
      - "9000:9000"

  php7.2:
    build: ./dockerfiles/php7.2
    networks:
      dev:
        aliases:
          - php
    volumes:
      - ./dockerfiles/php7.2/php-fpm.d:/usr/local/etc/php/php-fpm.d
      - ./dockerfiles/php7.2/conf.d:/usr/local/etc/php/conf.d
      - ./www:/var/www/html

  swoole:
    build: ./dockerfiles/swoole
    networks:
      dev:
        aliases:
          - php
    volumes:
      - ./www:/var/www/html
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"

  nginx:
    build: ./dockerfiles/nginx
    networks:
      dev:
        aliases:
          - nginx
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    ports:
      - "80:80"

  mysql:
    build: ./dockerfiles/mysql5.7
    networks:
      dev:
        aliases:
          - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./dockerfiles/mysql5.7/data:/var/lib/mysql
      - ./dockerfiles/mysql5.7/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  reids: 
    image: 'redis:5.0.4'
    networks: 
      dev:
        aliases:
          - redis
    volumes:
      - ./dockerfiles/redis:/data
    ports:
      - "6379:6379"
    command: [redis-server, /data/redis.conf]
      
networks:
  dev: