version: '3'

services:
  mariadb:
    image: 'luffyzhao/ubuntu-mariadb:v1.1'
    networks:
      dev:
        aliases:
          - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      # - ./data/mariadb:/var/lib/mysql
      - ./conf.d/mariadb:/etc/mysql/conf.d
    ports:
      - "3307:3306"
      
  php73-fpm:
    image: 'luffyzhao/php-fpm:v1.0'
    networks:
      dev:
        aliases:
          - php73-fpm
    volumes:
      - ./conf.d/php:/usr/local/etc/php
      - ./conf.d/php-fpm:/usr/local/etc/php-fpm.d
      - ./website:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: 'luffyzhao/nginx:v1.0'
    networks:
      dev:
        aliases:
          - nginx
    volumes:
      - ./conf.d/nginx:/etc/nginx/conf.d
      - ./website:/var/www/html
    ports:
      - "8080:80"
  
  easySwoole:
    image: 'luffyzhao/php-cli:v1.0'
    networks:
      dev:
        aliases:
          - easy-swoole
    volumes: 
      - ./website/easyswoole:/var/www
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    command: [/var/www/start.sh, /var/www, easyswoole, start]
  reids: 
    image: 'redis:5.0.3'
    networks: 
      dev:
        aliases:
          - redis
    volumes:
      - ./conf.d/redis:/var/local
    ports:
      - "6679:6379"
    command: [redis-server, /var/local/redis.conf]


networks:
  dev: