version: '3'

services:
  apache:
    image: luffyzhao/php:7.1-apache
    networks:
      dev:
        aliases:
          - apache
    volumes:
      - ./dockerfiles/php7.1-apache/conf-available:/etc/apache2/conf-available
      - ./dockerfiles/php7.1-apache/conf-enabled:/etc/apache2/conf-enabled
      - ./dockerfiles/php7.1-apache/sites-available:/etc/apache2/sites-available
      - ./dockerfiles/php7.1-apache/sites-enabled:/etc/apache2/sites-enabled
      - ./dockerfiles/php7.1-apache/mods-available:/etc/apache2/mods-available
      - ./dockerfiles/php7.1-apache/mods-enabled:/etc/apache2/mods-enabled
      - ./dockerfiles/php7.1-apache/conf.d:/usr/local/etc/php/conf.d
      - e:/www:/var/www/html
    ports:
      - "80:80"

  mysql:
    image: luffyzhao/mysql:5.7
    networks:
      dev:
        aliases:
          - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./dockerfiles/mysql5.7/data:/var/lib/mysql
      - ./dockerfiles/mysql5.7/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  reids: 
    image: luffyzhao/redis:5.0.4
    networks: 
      dev:
        aliases:
          - redis
    volumes:
      - ./dockerfiles/redis/data:/data
      - ./dockerfiles/redis/config:/var/www
    ports:
      - "6379:6379"
    command: [redis-server, /var/www/redis.conf]

  beanstalkd: 
    image: schickling/beanstalkd
    networks: 
      dev:
        aliases:
          - beanstalkd
    ports:
      - "11300:11300"

      
networks:
  dev: